spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_tdd
    username: root
    password: green502

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
  cache:
    disabled: true

file:
  directory: D:\2024-01\download\greengram_tdd

---

spring:
  config:
    activate:
      on-profile: tdd
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_tdd_test
  sql:
    init:
      mode: always

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.144:3306/db_odd_first_5
    username: odd_first_5
    password: intel

file:
  directory: /home/download



